application: chickenaday
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /
  static_files: index.html
  upload: index\.html
  
- url: /static
  static_dir: static

- url: /account
  script: account.app
  login: required

- url: /confirm
  script: account.app

- url: /unsubscribe
  script: account.app
  
- url: /send
  script: send.app
  login: admin

- url: /image/store
  script: photo.app
  login: admin
  
- url: /image/.*
  script: photo.app
  
  
- url: /terms
  script: general.app
- url: /privacy
  script: general.app
- url: /reportBad
  script: general.app

libraries:
- name: webapp2
  version: "2.5.2"
